name: "Project Upload"
description: "Upload and build a HubSpot project in your account. If auto-deploy is enabled, the build will also be deployed to your account."
inputs:
  project_dir:
    description: "The path to the directory where your hsproject.json file is located"
    required: true
    default: ./
    type: string
  personal_access_key:
    description: "[SECRET] Personal Access Key generated in HubSpot that grants access to the CLI. If not provided, will use DEFAULT_PERSONAL_ACCESS_KEY from environment."
    required: false
    type: string
  account_id:
    description: "HubSpot account ID associated with the personal-access-key. If not provided, will use DEFAULT_ACCOUNT_ID from environment."
    required: false
    type: number
  cli_version:
    description: "Version of the HubSpot CLI to install. If not provided, will use DEFAULT_CLI_VERSION from environment. If neither are found, defaults to a pre-determined stable version of the CLI"
    required: false
    type: string
  profile:
    description: "Profile to use for the HubSpot CLI. If not provided, will use DEFAULT_PROFILE from environment."
    required: false
    type: string
  debug:
    description: "Enable debug mode for HubSpot CLI commands. Passes --debug flag to all hs commands. If not provided, will use DEFAULT_DEBUG from environment."
    required: false
    type: boolean
outputs:
  build_id:
    description: "The build ID of the created HubSpot project build"
  deploy_id:
    description: "The deploy ID if auto-deploy is enabled"
runs:
  using: "composite"
  steps:
    - name: Install HubSpot CLI
      uses: HubSpot/hubspot-project-actions/install-hubspot-cli@v1.0.1
      with:
        cli_version: ${{ inputs.cli_version }}
    - name: Upload source code to HubSpot Project
      shell: bash
      env:
        HUBSPOT_PERSONAL_ACCESS_KEY: ${{ inputs.personal_access_key || env.DEFAULT_PERSONAL_ACCESS_KEY }}
        HUBSPOT_ACCOUNT_ID: ${{ inputs.account_id || env.DEFAULT_ACCOUNT_ID }}
        HUBSPOT_PROFILE: ${{ inputs.profile || env.DEFAULT_PROFILE }}
        DEBUG_MODE: ${{ inputs.debug || env.DEFAULT_DEBUG}}
      run: |
        # Source shared utilities
        . "$GITHUB_ACTION_PATH/../scripts/action-utils.sh"

        # Validate account and personal access key
        validate_account_and_personal_access_key

        # Resolve and validate project directory
        resolve_project_dir "${{ inputs.project_dir }}"

        # Handle profile usage
        PROFILE_ARG=""
        if [ -n "$HUBSPOT_PROFILE" ]; then
          PROFILE_ARG="--profile $HUBSPOT_PROFILE"
        fi

        # Run upload command
        run_hs_command \
          "hs project upload --force-create --use-env --json --message '${{ github.event.head_commit.message || 'Uploaded via HubSpot GitHub Action' }} (${GITHUB_SHA:0:7})' $PROFILE_ARG" \
          "true"

        # Parse and set outputs
        set_output_from_json "build_id" ".buildId"
        set_output_from_json "deploy_id" ".deployId" "true"

        echo "✅ Project upload completed successfully"
