name: "Install HubSpot CLI"
description: "Install the HubSpot CLI"
inputs:
  cli_version:
    description: "Version of the HubSpot CLI to install. If not provided, will look for DEFAULT_CLI_VERSION in environment. If neither are found, defaults to latest."
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Install HubSpot CLI
      shell: bash
      run: |
        # Get CLI version from input or environment, defaulting to latest
        CLI_VERSION="${{ inputs.cli_version || env.DEFAULT_CLI_VERSION || '7.9.0' }}"

        # Check if hs CLI is already installed with correct version
        if ! command -v hs &> /dev/null || [[ "$CLI_VERSION" != "latest" && ! "$(hs --version)" =~ "$CLI_VERSION" ]]; then
          echo "Installing HubSpot CLI version $CLI_VERSION"
          npm install -g "@hubspot/cli@$CLI_VERSION"
        else
          echo "HubSpot CLI is already installed with correct version"
        fi
